version: '3'
services:

  karmabot:
    build:
      context: .
      dockerfile: Dockerfile

    image: target/karmabot:local
    ports:
      - 5000:5000
    cap_add:
      - ALL
    environment:
      - RUNTIME_LOG_LEVEL=debug
      - LOG_LEVEL=DEBUG
      - MONGODB=mongodb+srv://username:password@karmabot.subdomain.mongodb.net/?retryWrites=true&w=majority&appName=Karmabot
      - VERIFICATION_TOKEN=token
      - ACCESS_T039J07M3M0=datadog-sandbox-token
      - BOT_T039J07M3M0=datadog-sandbox-bot-token
      - KARMA_TTL=36500

